artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/JavithNaseem-J/Booking.com_SQL/raw/refs/heads/main/archive.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/data.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv
  target_column: Price
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl



model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train_processed.npy
  test_data_path: artifacts/data_transformation/test_processed.npy
  model_name: model.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_path: artifacts/model_evaluation/metrics.json
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl